#!/usr/bin/with-contenv bash

PUID=${PUID:-1026}
PGID=${PGID:-100}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)

-------------------------------------
"
chown -R abc:abc /config
chown -R abc:abc /downloads
