#!/usr/bin/with-contenv bash

# 检查config配置文件，并创建
if [ ! -e "/config/config/qBittorrent.conf" ] ;  then 
mkdir -p /config/config
cp /usr/local/qbittorrent/defaults/qBittorrent.conf  /config/config/qBittorrent.conf
fi

# 检查Search文件，并创建.
if [ ! -d "/config/data/nova3/engines" ] ;  then 
mkdir -p /config/data/nova3/engines
fi
cp -ru /usr/local/qbittorrent/defaults/Search/*  /config/data/nova3/engines

# permissions
chown -R abc:abc \
	/config \
    /downloads